/**
 * @type {import('node-pg-migrate').ColumnDefinitions | undefined}
 */
exports.shorthands = undefined;

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
exports.up = (pgm) => {
  pgm.sql(`
    CREATE TYPE expense_frequency AS ENUM (
      'week',
      'month',
      'year'
    );

    CREATE TABLE expense_types (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      frequency expense_frequency NOT NULL,
      budget INTEGER NOT NULL CHECK (budget >= 0),
      description TEXT,
      created_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE expenses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
      expense_type_id BIGINT NOT NULL REFERENCES expense_types(id),
      created_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE budgets (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
      created_at TIMESTAMPTZ DEFAULT now()
    );

    CREATE TABLE surpluses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      amount NUMERIC(12, 2) NOT NULL
    );

    CREATE INDEX idx_expenses_expense_type_id ON expenses (expense_type_id);
  `);
};

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
exports.down = (pgm) => {
  pgm.sql(`
    DROP TABLE budgets;
    DROP TABLE expenses;
    DROP TABLE expense_types;
    DROP TABLE surpluses;

    DROP TYPE expense_frequency;
  `);
};
